{
  "name": "baloy-space",
  "version": "1.0.0",
  "description": "Baloy Space",
  "private": true,
  "scripts": {
    "build": "echo No web build required",
    "sync": "npx cap sync android",
    "android": "npx cap open android"
  },
  "dependencies": {
    "@capacitor/core": "^7.6.0"
  },
  "devDependencies": {
    "@capacitor/android": "^7.6.0",
    "@capacitor/cli": "^7.6.0"
  }
}
